/* eslint-disable */
import Head from "next/head";
import Image from "next/image";

import { useUser } from "@clerk/nextjs";



import { api } from "~/utils/api";





export default function SinglePostPage() {
 
  

  return (
    <>
      <Head>
        <title>post</title>
        <meta name="description" content="Generated by create-t3-app" />
        
      </Head>
      <main className='flex h-screen justify-center'>
        
        <div>
          post view
        
        </div>
      </main>
    </>
  );
}
